apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: default-receiver
    receivers:
      - name: default-receiver
        email_configs:
          - to: "your-email@example.com"

