apiVersion: v1
kind: Service
metadata:
  name: recallrisk-service
  namespace: default
  labels:
    app: recallrisk
spec:
  type: LoadBalancer
  selector:
    app: recallrisk
  ports:
    - name: http      
      protocol: TCP
      port: 9090
      targetPort: 5000    


