apiVersion: v1
kind: Service
metadata:
  name: recallrisk-service
  namespace: default
  labels:
    app: recallrisk
spec:
  type: NodePort   # 👈 Expose outside the cluster
  selector:
    app: recallrisk
  ports:
    - name: http-metrics
      port: 8080         # Service port inside cluster
      targetPort: 5000   # Container port
      protocol: TCP
      nodePort: 30080    # 👈 You can specify, or remove this line to let Kubernetes assign one automatically



