name: EKS CI/CD Pipeline

on:
  push:
    # Trigger on push to the main branch
    branches: [ main ]
  pull_request:
    # Trigger on pull request targeting the main branch
    branches: [ main ]

env:
  # AWS and ECR configuration
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  
  # EKS configuration
  KUBE_CLUSTER_NAME: ${{ secrets.KUBE_CLUSTER_NAME }}
  KUBE_DEPLOYMENT_NAME: recallrisk-deployment # Name of your Kubernetes Deployment
  KUBE_CONTAINER_NAME: recallrisk             # Name of the container in the Deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit SHA as unique tag
        id: set_tag
        run: |
          # Use the first 7 characters of the commit SHA as the unique image tag
          echo "IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      # --- CI: Build & Test Stage (Example) ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Add Unit Tests step here if applicable:
      # - name: Run Unit Tests
      #   run: python -m unittest discover

      # --- CD: Containerization & Push Stage ---
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        # Use the official action for a cleaner and more secure login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          # 1. Build using the unique commit SHA tag
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          
          # 2. Tag with the full ECR path
          FULL_IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $FULL_IMAGE_NAME
          
          # 3. Push the uniquely tagged image to ECR
          docker push $FULL_IMAGE_NAME
          
      # --- CD: Deployment Stage to EKS ---
      - name: Update Kubeconfig
        # This step uses the AWS credentials to update the runner's kubectl context
        run: aws eks update-kubeconfig --name $KUBE_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy new image to EKS
        run: |
          FULL_IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Use the unique tag for the deployment update
          # This command updates the image for the specified container within the deployment
          kubectl set image deployment/$KUBE_DEPLOYMENT_NAME $KUBE_CONTAINER_NAME=$FULL_IMAGE_NAME
          
          # Wait for the rollout to complete before finishing the workflow
          kubectl rollout status deployment/$KUBE_DEPLOYMENT_NAME
